//
// Created by 86136 on 2023/5/9.
//

#ifndef WINDMILL_MASTERCONTROL_CODE_BSP_UART_H
#define WINDMILL_MASTERCONTROL_CODE_BSP_UART_H

void uart_IT(unsigned char *fsm_state);

#endif //WINDMILL_MASTERCONTROL_CODE_BSP_UART_H
